//Helpers
import update from 'immutability-helper';

export default (state = [
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
        {
          name: "Javascript",
          totalQuestions: 20,
          qustionsForQuiz: 10,
          timeLimit: 30,
          passingScore: 50,
          active: true,
        },     
], action) => {
    switch (action.type) {
        case 'CREATE_QUIZ':
            return update(state, {$push: [action.quiz]});
        case 'EDIT_QUIZ':
            return update(state, {$splice: [[action.index, 1, action.quiz]]});
        case 'DLT_QUIZ':
            return update(state, {$splice: [[action.index, 1]]});
        default:
            return state;
    }
}